site_name: Islandora CLAW
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora CLAW

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora-CLAW/CLAW

theme: material

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'assets/claw.png'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/islandora'

pages:

- User Documentation:
    - 'Introduction to Islandora CLAW': 'user-documentation/intro-to-claw.md'
    - 'Islandora CLAW for 1.x Users': 'user-documentation/CLAWfor1x.md'
    - 'Behold CLAW': 'user-documentation/behold-claw.md'
- Technical Documentation:
    - 'Minimum Viable Product': 'mvp/mvp_doc.md'
    - 'How to build documenation': 'technical-documentation/docs-build.md'
    - 'Syncing Drupal Project': 'technical-documentation/drupal-project.md'
    - 'Versioning Policy': 'technical-documentation/versioning.md'
    - 'Alpaca Technical Stack': 'alpaca/alpaca-technical-stack.md'
- Components:
    - 'Islandora CLAW': 'index.md'
    - 'Alpaca': 'alpaca/README.md'
    - 'Chullo': 'chullo/README.md'
    - 'Crayfish': 'crayfish/README.md'
    - 'Crayfish-Commons': 'crayfish-commons/README.md'
    - 'Syn': 'syn/README.md'
    - Drupal modules:
      - 'Islandora': 'islandora/README.md'
      - 'Islandora Collection': 'islandora_collection/README.md'
      - 'Islandora Image': 'islandora_image/README.md'
      - 'jsonld': 'jsonld/README.md'
- Installation:
    - 'Installation (Vagrant)': 'install/README.md'
- Contributing:
    - 'How to contribute': 'contributing/CONTRIBUTING.md'
    - 'Committers': 'contributing/committers.md'
    - 'Hacking on Islandora': 'contributing/hacking-on-islandora.md'
- Migration:
    - 'Migration': 'migration/migration.md'
    - 'Fedora namespace predicates': 'migration/fedora-namespace-predicates.md'
    - 'Islandora namespace predicates': 'migration/islandora-namespace-predicates.md'
